#!/bin/bash

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
 
echo -e $(date +"%d/%m/%y %H:%M") "|" $(git log --pretty=format:"%h" -1 HEAD) "["$(git rev-parse --abbrev-ref HEAD)"]" $(git log --pretty=format:"%s" -1 HEAD) >> ~/src/commits

echo $LC