#!/bin/bash
set +x

if git rev-parse --verify HEAD >/dev/null 2>&1; then
    against=HEAD
else
    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
 
for FILE in `git diff-index --name-status $against -- | cut -c3-` ; do
    # Check if the file contains 'debugger'
    if  git diff --cached -- "$FILE" | grep -q -e '//!!' -e 'debugger'
    then
    	echo '---------------------------'
    	echo 'Uncommittable data detected'
    	echo -e '---------------------------\n'
        grep -Hn --context 2 -e '//!!' -e 'debugger' $FILE
        exit 1
    fi
done
exit 
